# Generated by Django 5.2 on 2025-07-19 10:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0004_user_age_user_country_user_createdat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='about',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='state',
        ),
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
        migrations.RemoveField(
            model_name='user',
            name='createdAt',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='user',
            name='usertype',
        ),
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.PositiveIntegerField(default=18),
        ),
        migrations.AddField(
            model_name='profile',
            name='createdAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='profile',
            name='height_cm',
            field=models.IntegerField(default=170),
        ),
        migrations.AddField(
            model_name='profile',
            name='position',
            field=models.CharField(default='Employee', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='strong_foot',
            field=models.CharField(choices=[('left', 'Left'), ('right', 'Right')], default='Right', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='usertype',
            field=models.CharField(choices=[('Player', 'Player'), ('Manager', 'Manager')], default='Player', max_length=10),
        ),
    ]
